### ISSUE TITLE
Unclear error message thrown by stft if input and window arguments are on different devices

### ISSUE THREAD

**Issue by zhangshenyu7105** [usc-sail/gard-adversarial-speaker-id#2]
Today, I upgraded to latest n' greatest Pytorch 1.9, and now it's throwing at error.
''RuntimeError: stft input and window must be on the same device but got self on cuda:0 and window on cpu''

**Comment by zhangshenyu7105** [comment]
Traceback (most recent call last):
  File "train_libri.py", line 238, in <module>
    main(parse_args())
  File "train_libri.py", line 113, in main
    real_feature = model.encode(inputs)
  File "/home/ics/gard-adversarial-speaker-id-master/dev/models/model.py", line 84, in encode
    x = self.prep(x.squeeze(1))
  File "/home/ics/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ics/gard-adversarial-speaker-id-master/dev/transforms/dataset.py", line 111, in forward
    window=torch.hann_window(hp.win_length))
  File "/home/ics/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/functional.py", line 472, in stft
    normalized, onesided, return_complex)
RuntimeError: stft input and window must be on the same device but got self on cuda:0 and window on cpu
